
export const ELECTION_STATES = {
  NOT_LOGGED_IN: 'NOT_LOGGED_IN',
  LOGGED_IN: 'LOGGED_IN',
  VOTED: 'VOTED',
};

export const ELECTION_TRANSITIONS = {
  [ELECTION_STATES.NOT_LOGGED_IN]: {
    LOGIN: ELECTION_STATES.LOGGED_IN,
  },
  [ELECTION_STATES.LOGGED_IN]: {
    VOTE: ELECTION_STATES.VOTED,
    LOGOUT: ELECTION_STATES.NOT_LOGGED_IN,
  },
  [ELECTION_STATES.VOTED]: {
    CONFIRM: ELECTION_STATES.NOT_LOGGED_IN,
  },
};
