export const ELECTION_STATES = {
  NOT_LOGGED_IN: 'NOT_LOGGED_IN',
  LOGGED_IN: 'LOGGED_IN',
  VOTED: 'VOTED',
  LOGOUT: "LOGOUT"
};
export const ELECTION_ACTIONS = {
  LOGIN: 'LOGIN',
  VOTE: 'VOTE',
  NOT_LOGGED_IN: 'NOT_LOGGED_IN',
  LOGOUT: 'LOGOUT',
};
export const ELECTION_TRANSITIONS = {
  [ELECTION_STATES.NOT_LOGGED_IN]: {
    LOGIN: ELECTION_STATES.LOGGED_IN,
  },
  [ELECTION_STATES.LOGGED_IN]: {
    VOTE: ELECTION_STATES.VOTED,
  },
  [ELECTION_STATES.VOTED]: {
    LOGOUT: ELECTION_STATES.LOGOUT,
  },
  [ELECTION_STATES.LOGOUT]: {
    LOGOUT: ELECTION_STATES.NOT_LOGGED_IN,

  },
};
